# fly.toml app configuration file generated for beon-intermedia-db on 2023-09-30T14:12:05+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beon-intermedia-db"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
