export const iconMaps: any = {
  add: 'img:/icons/add.svg',
  add_box: 'img:/icons-color/add-square-white.svg',
  add_square: 'img:/icons/add-square.svg',
  alert_circle_white: 'img:/icons-color/alert-circle-outline.svg',
  arrow_down: 'img:/icons/arrow-down-1.svg',
  arrow_down_primary: 'img:/icons-color/arrow-down-primary.svg',
  arrow_drop_down: 'img:/icons/arrow-down-1.svg',
  arrow_up: 'img:/icons/arrow-up-1.svg',
  arrow_up_primary: 'img:/icons-color/arrow-up-primary.svg',
  arrow_left: 'img:/icons/arrow-left-1.svg',
  arrow_left_solid: 'img:/icons/arrow-left-solid.svg',
  arrow_right: 'img:/icons/arrow-right-1.svg',
  attach: 'img:/icons/attach.svg',
  broadcast: 'img:/icons/megaphone-newer.svg',
  broadcast_alt: 'img:/icons/megaphone-outline.svg',
  calendar: 'img:/icons/calendar.svg',
  calendar_edit: 'img:/icons/calendar-edit.svg',
  chart_bar: 'img:/icons/chart-square.svg',
  chat_bot: 'img:/icons/chatbot.svg',
  chat_bot_primary: 'img:/icons-color/chatbot-primary.svg',
  check: 'img:/icons/check-solid.svg',
  check_white: 'img:/icons-color/check-solid-white.svg',
  check_double: 'img:/icons/check-double-solid.svg',
  check_bold: 'img:/icons/tick-circle.svg',
  check_square: 'img:/icons/tick-square.svg',
  chevron_left: 'img:/icons/arrow-left-1.svg',
  chevron_right: 'img:/icons/arrow-right-1.svg',
  cancel: 'img:/icons/close-circle.svg',
  close: 'img:/icons/times-solid.svg',
  close_circle: 'img:/icons/close-circle.svg',
  close_square: 'img:/icons/close-square.svg',
  command: 'img:/icons/command-square.svg',
  command_primary: 'img:/icons-color/command-square-primary.svg',
  document: 'img:/icons/document-1.svg',
  download: 'img:/icons/download.svg',
  edit: 'img:/icons/edit.svg',
  edit_text: 'img:/icons/edit-2.svg',
  edit_text_white: 'img:/icons-color/edit-2-white.svg',
  eye: 'img:/icons/eye.svg',
  eye_slash: 'img:/icons/eye-slash.svg',
  filter: 'img:/icons/filter.svg',
  happy: 'img:/icons/happyemoji.svg',
  headphone: 'img:/icons/headset-newer.svg',
  headphone_primary: 'img:/icons-color/headset-newer-primary.svg',
  headphone_alt: 'img:/icons/headset-solid.svg',
  home: 'img:/icons/home-2.svg',
  info_circle: 'img:/icons/info-circle.svg',
  info_circle_bold: 'img:/icons/info-circle-bold.svg',
  import: 'img:/icons/import.svg',
  like_tag: 'img:/icons/like-tag.svg',
  like_tag_primary: 'img:/icons-color/like-tag-primary.svg',
  link: 'img:/icons/link-2.svg',
  keyboard: 'img:/icons/keyboard.svg',
  keyboard_primary: 'img:/icons-color/keyboard-primary.svg',
  message: 'img:/icons/message.svg',
  message_primary: 'img:/icons-color/message-primary.svg',
  message_notif: 'img:/icons/message-notif.svg',
  message_text: 'img:/icons/message-text-1.svg',
  message_inbox: 'img:/icons/directbox-receive.svg',
  message_outbox: 'img:/icons/directbox-send.svg',
  mouse_square: 'img:/icons/mouse-square.svg',
  notification: 'img:/icons/notification.svg',
  people: 'img:/icons/people.svg',
  people_primary: 'img:/icons-color/people-primary.svg',
  receipt: 'img:/icons/receipt-item.svg',
  search: 'img:/icons/search-normal.svg',
  send: 'img:/icons/send-1.svg',
  send_bold: 'img:/icons/send-1-bold.svg',
  send_up: 'img:/icons/send-2.svg',
  setting: 'img:/icons/setting-2.svg',
  signout: 'img:/icons/logout.svg',
  ticket: 'img:/icons/ticket.svg',
  time: 'img:/icons/timer-1.svg',
  trash: 'img:/icons/trash.svg',
  user: 'img:/icons/profile.svg',
  user_check: 'img:/icons/profile-tick.svg',
  user_edit: 'img:/icons/user-edit.svg',
  user_rounded_primary: 'img:/icons-color/user-rounded-primary.svg',
  users: 'img:/icons/profile-2user.svg',
  warning: 'img:/icons/warning-2.svg',
  first_page: 'img:/icons/angle-double-left-solid.svg',
  last_page: 'img:/icons/angle-double-right-solid.svg',
  brand_facebook: 'img:/brands/facebook.svg',
  brand_instagram: 'img:/brands/instagram.png',
  brand_telegram: 'img:/brands/telegram.svg',
  brand_tiktok: 'img:/brands/tiktok.png',
  brand_whatsapp: 'img:/brands/whatsapp.svg',
  brand_whatsapp_business: 'img:/brands/whatsapp-business.svg',
}

export const sidebarMaps: any = [
  { id: 'dashboard', icon: 'home', text: 'Dashboard', path: '/' },
  { id: 'due', icon: 'receipt', text: 'Iuran', path: '/due' },
  { id: 'occupant', icon: 'people', text: 'Penghuni', path: '/occupant' },
  { id: 'house', icon: 'home', text: 'Rumah', path: '/house' },
  { id: 'payment', icon: 'receipt', text: 'Pembayaran', path: '/payment' },
  { id: 'report', icon: 'chart_bar', text: 'Report', path: '/report' },
  {
    id: 'logout',
    icon: 'signout',
    text: 'Logout',
    isLogout: true,
  },
].filter((item: any) => !item.hidden)

export const userMenuMaps: any = [
  { id: 'profile', icon: 'user_edit', text: 'Edit Profile', path: '/user-edit' },
  { id: 'divider-1', type: 'divider' },
  { id: 'logout', icon: 'logout', text: 'Log Out' },
]

